project_name: Plywood Gallery - Functions
repository_url: https://github.com/kolibril13/further_ideas_plywood_gallery
user_content_version: 0.11.2 (Seaborn)
description: |
  Normal cells are independent of each other, and can be run togehter with the "Header" cell. 
favicon: icon.png
custom_footer: |
  <div style="position: fixed; bottom: 10px; right:10px" >
      <a href="web1_ImageGrid.html"> ImageGrid</a>
        <!-- <a href="web2_Numpy.html"> Numpy</a>  <br> -->
      <a href="web3_2DArray.html"> 2D Arrays</a>
      <a href="web4_3DArray.html"> 3D Arrays</a> 
      <a href="web5_functions.html"> Functions</a> 
      <a href="web6_Pathlib.html"> Pathlib</a> 
      <a href="web7_NumberFormatting.html"> f-String</a> 
      &#160 &#160
  </div>
gallery_parameters_path: gallery_assets_5_Functions/gallery_parameters.json




