project_name: Plywood Gallery - 2DArray
repository_url: https://github.com/kolibril13/further_ideas_plywood_gallery
description: |
  Normal cells are independent of each other, and can be run togehter with the "Header" cell. <br>
  A "Dependent" cell depends on the "Normal" cell left to it. <br>
  A "Dependent" cell depends on another "Dependent" cell left to it.
favicon: icon.png
custom_footer: |
  <div style="position: fixed; bottom: 10px; right:10px" >
      <a href="web1_ImageGrid.html"> ImageGrid</a>
      <a href="web2_Numpy.html"> Numpy</a>
      <a href="web3_2DArray.html"> 2D Arrays</a>
      <a href="web4_3DArray.html"> 3D Arrays</a> 
      &#160 &#160
  </div>
gallary_parameters_path: gallery_assets_2DArray/gallery_parameters.json




